title: Ayush Kumar
description: AI & ML Enthusiast | Research Intern at IIT Bombay & SRM IST
url: "https://zmey1.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# We’re not using separate pages anymore
header_pages: []

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: null
