title: Ayush Kumar
description: AI & ML Enthusiast | Research Intern at IIT Bombay & SRM IST
theme: jekyll-theme-tactile

# Optional: add social links or footer
github:
  is_project_page: false

# For GitHub Pages
plugins:
  - jekyll-seo-tag

# Remove remote_theme – not used for GitHub themes
# remote_theme: mmistakes/minimal-mistakes
